{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-context-support",
    "version": "6.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-support-6.1.6.jar",
          "url": "spring-context-support-6.1.6.jar",
          "size": 173297,
          "sha512": "82f8fe4eb3bd776c0ea866eb5b11a3b5a1fbbc83348abe6d7c22fb5767fcac1ef4955969378d7a63059df4445fac059724e6f175099932cae95c381fa28bc3b0",
          "sha256": "0f62f0fef682b9ca10e83a292d01e934f0cb38207b07521bcb57e71050523fef",
          "sha1": "7cc404d7f0c6e1b1ecfa30080fe194b52867d6b2",
          "md5": "8d5862cfaec6d2d9b6292992317859cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-support-6.1.6.jar",
          "url": "spring-context-support-6.1.6.jar",
          "size": 173297,
          "sha512": "82f8fe4eb3bd776c0ea866eb5b11a3b5a1fbbc83348abe6d7c22fb5767fcac1ef4955969378d7a63059df4445fac059724e6f175099932cae95c381fa28bc3b0",
          "sha256": "0f62f0fef682b9ca10e83a292d01e934f0cb38207b07521bcb57e71050523fef",
          "sha1": "7cc404d7f0c6e1b1ecfa30080fe194b52867d6b2",
          "md5": "8d5862cfaec6d2d9b6292992317859cb"
        }
      ]
    }
  ]
}
