{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-test",
    "version": "6.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-test-6.2.4.jar",
          "url": "spring-security-test-6.2.4.jar",
          "size": 132223,
          "sha512": "082f05e0eef55d39e764d8526039e83f41f4bee4126b35c1efebd913fb54004f7be51d0800eed5280fb26795d68639b688e3d1f07201129bfe2f70f17f985862",
          "sha256": "3a075366809db44e2c78e8f2076288ae312258e255c66ccdb26aa5ae0aad1824",
          "sha1": "81ada37bf96d07d8e287a6a683c6dd3cdaa90671",
          "md5": "f94862483ac77e899cbdd0bb205bf6d7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-test-6.2.4.jar",
          "url": "spring-security-test-6.2.4.jar",
          "size": 132223,
          "sha512": "082f05e0eef55d39e764d8526039e83f41f4bee4126b35c1efebd913fb54004f7be51d0800eed5280fb26795d68639b688e3d1f07201129bfe2f70f17f985862",
          "sha256": "3a075366809db44e2c78e8f2076288ae312258e255c66ccdb26aa5ae0aad1824",
          "sha1": "81ada37bf96d07d8e287a6a683c6dd3cdaa90671",
          "md5": "f94862483ac77e899cbdd0bb205bf6d7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-test-6.2.4-javadoc.jar",
          "url": "spring-security-test-6.2.4-javadoc.jar",
          "size": 233746,
          "sha512": "467c885ca18033f2acde00c6de2dd88c2098707ca15d3ccc05e35e9bda005ec1114fdd1beadf5eae27d97c0cd4a5729f1a44f5e9d8244a7bd1a8b4e16680be01",
          "sha256": "ab695c3cdf2cf9b54642cc45c68f2db681ce7310ab3af46fe164c9b3b6e5a2e2",
          "sha1": "d71bd78326ef3754c6b7bd3a016e1dbbcf23d8a4",
          "md5": "d369672bb1437ee8892b8130c3dac5fc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-test-6.2.4-sources.jar",
          "url": "spring-security-test-6.2.4-sources.jar",
          "size": 56481,
          "sha512": "d759fbc85e974de12623ffd00e43a2f4e92e7e730103217790fcdca18605896259c0fb770ed79dcb4dc09815a25950c17f7635105b5b8d12abac264b10695792",
          "sha256": "538dd4d23553936be5bb353de4386f5348ab918faf45321ab0c59e239c818458",
          "sha1": "471a140bcc8e8a7f949323bb79ff37cb524533f7",
          "md5": "a8a3e0f2f09c517cd85188da48e8c9d3"
        }
      ]
    }
  ]
}
