{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-redis",
    "version": "3.2.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.3.2.RELEASE"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-redis",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.2.5.jar",
          "url": "spring-boot-starter-data-redis-3.2.5.jar",
          "size": 4785,
          "sha512": "fa03fe7fa04d7c1dbeb8e18471a88fd5bdad58d0d78cfc39ce4000aab5290e375606e5fe5b5a5d6bfa34c8dbf55368c1f1c9f223aa10bc5f5f96d3c62dcdf7e5",
          "sha256": "d80ff8dd94d9cadc0800bad719d8475206b5bd8f47020ee112a271dedd28fa83",
          "sha1": "5c28002231949d324d5c5a06e0a1768103b3075f",
          "md5": "3b1d6146c57d3a79c3b2c2344198b7c3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.3.2.RELEASE"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-redis",
          "version": {
            "requires": "3.2.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.2.5.jar",
          "url": "spring-boot-starter-data-redis-3.2.5.jar",
          "size": 4785,
          "sha512": "fa03fe7fa04d7c1dbeb8e18471a88fd5bdad58d0d78cfc39ce4000aab5290e375606e5fe5b5a5d6bfa34c8dbf55368c1f1c9f223aa10bc5f5f96d3c62dcdf7e5",
          "sha256": "d80ff8dd94d9cadc0800bad719d8475206b5bd8f47020ee112a271dedd28fa83",
          "sha1": "5c28002231949d324d5c5a06e0a1768103b3075f",
          "md5": "3b1d6146c57d3a79c3b2c2344198b7c3"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.2.5.jar",
          "url": "spring-boot-starter-data-redis-3.2.5.jar",
          "size": 4785,
          "sha512": "fa03fe7fa04d7c1dbeb8e18471a88fd5bdad58d0d78cfc39ce4000aab5290e375606e5fe5b5a5d6bfa34c8dbf55368c1f1c9f223aa10bc5f5f96d3c62dcdf7e5",
          "sha256": "d80ff8dd94d9cadc0800bad719d8475206b5bd8f47020ee112a271dedd28fa83",
          "sha1": "5c28002231949d324d5c5a06e0a1768103b3075f",
          "md5": "3b1d6146c57d3a79c3b2c2344198b7c3"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-redis-maven-optional",
          "version": "3.2.5"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.2.5.jar",
          "url": "spring-boot-starter-data-redis-3.2.5.jar",
          "size": 4785,
          "sha512": "fa03fe7fa04d7c1dbeb8e18471a88fd5bdad58d0d78cfc39ce4000aab5290e375606e5fe5b5a5d6bfa34c8dbf55368c1f1c9f223aa10bc5f5f96d3c62dcdf7e5",
          "sha256": "d80ff8dd94d9cadc0800bad719d8475206b5bd8f47020ee112a271dedd28fa83",
          "sha1": "5c28002231949d324d5c5a06e0a1768103b3075f",
          "md5": "3b1d6146c57d3a79c3b2c2344198b7c3"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-redis-maven-optional",
          "version": "3.2.5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.2.5-javadoc.jar",
          "url": "spring-boot-starter-data-redis-3.2.5-javadoc.jar",
          "size": 4748,
          "sha512": "2966f0614c6338c0a48e0c7b1a7aa12f00057e8e588072f9f7b12fe42acf14e6dfb120956446243bf2b69e571cc913588ad4b210ce453c571367ae60cdf11924",
          "sha256": "b4107c83c09756cbbecda70a52a977285f2aab639ece248ff70312f973d8efc0",
          "sha1": "200f44712d3369e5bb1e35483dbf36520de03b63",
          "md5": "d07bbb3e17a19f6bc9b85d196325639a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.2.5-sources.jar",
          "url": "spring-boot-starter-data-redis-3.2.5-sources.jar",
          "size": 4747,
          "sha512": "d3c6324db790e8aff5c2072a42c33085fd0d86c538a43b8c6cabb6106e6a111dfd6592742dca8c8dfb1088af224a581a3d3171ac8e133c0650338bd7d37ae8b0",
          "sha256": "5af49152a07faf1fc036b3ec7174363e569cf59e47d0fb7fb64bc158c520a3b5",
          "sha1": "9f70e60ce72db0526e32739ec861c93df2ac99ce",
          "md5": "9ffa3ba11f1cd8beaebaf53e6e3cf8fb"
        }
      ]
    }
  ]
}
