{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-crypto",
    "version": "6.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.2.4.jar",
          "url": "spring-security-crypto-6.2.4.jar",
          "size": 84190,
          "sha512": "14898057dcdd730796e5d79b614f01e16421d1122258cb41e2347d6ed6a2029a8f97a549f9e4f036854a96229165ad0daacf31f410d0be012e1d382f54583201",
          "sha256": "5a36c1f29d11f0b9ce4b7c54886bd909499eadb0b19be507b6b3992830af23b6",
          "sha1": "9583253c66bafe7cbf0f082d069b08675331ce78",
          "md5": "bdb444acaeb4a10225af21e068070af2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.2.4.jar",
          "url": "spring-security-crypto-6.2.4.jar",
          "size": 84190,
          "sha512": "14898057dcdd730796e5d79b614f01e16421d1122258cb41e2347d6ed6a2029a8f97a549f9e4f036854a96229165ad0daacf31f410d0be012e1d382f54583201",
          "sha256": "5a36c1f29d11f0b9ce4b7c54886bd909499eadb0b19be507b6b3992830af23b6",
          "sha1": "9583253c66bafe7cbf0f082d069b08675331ce78",
          "md5": "bdb444acaeb4a10225af21e068070af2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.2.4-javadoc.jar",
          "url": "spring-security-crypto-6.2.4-javadoc.jar",
          "size": 225081,
          "sha512": "554bf16c561116b5d82ad6a6d598c71c3d207b4cf7dd2c3b7e053b45f7c5de9088461b5e603af908c365d675e1728f5ec524b0bfc9386052b90faeaa8cd8b91b",
          "sha256": "161e2104effb9d779225d0c42a9ce5e187ad3584d102ffa581606f4b5f7bd827",
          "sha1": "80f6cdfe4178e098fc5ea0e79760fdf5361c9c2d",
          "md5": "d89864153430e8e796ca2e418359e843"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-crypto-6.2.4-sources.jar",
          "url": "spring-security-crypto-6.2.4-sources.jar",
          "size": 76810,
          "sha512": "b2a0011c900e2e0ec800b2ad6083b3c96a8e8efc8fe33c954c589128bcd60ec1b7b229259df7b4b9fb927080011096fc3a448b3d1bc18c30f06da9e4db33b4b9",
          "sha256": "a7e6cbce2d61062fea3d0fcdfecae17227ca7e6d767bc6ae0f612d98025fbea7",
          "sha1": "7aef65c36d6c3d11eedae3015fc011097668ace4",
          "md5": "5b48fa4fc8544a2d310b1f56b03d311c"
        }
      ]
    }
  ]
}
