{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-config",
    "version": "6.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-config-6.2.4.jar",
          "url": "spring-security-config-6.2.4.jar",
          "size": 1813234,
          "sha512": "c6394c912d3dfbb9c1514d0756fe388d58b8471b2dbe2a9baecd981e741b3697b2d4b06e4f761dd91b0fe2cc8e7e6742b85e47d6120a204f70ed9fad7829cf03",
          "sha256": "a68a43a5fc40c2bb04718296a00142ee5240ceb5dfa50807d19a98c7e245b7e7",
          "sha1": "ef1f16ce7900f602826b985f15b67bbe60015a08",
          "md5": "a89de3fa1c4e19fc8796e776ab58428d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-config-6.2.4.jar",
          "url": "spring-security-config-6.2.4.jar",
          "size": 1813234,
          "sha512": "c6394c912d3dfbb9c1514d0756fe388d58b8471b2dbe2a9baecd981e741b3697b2d4b06e4f761dd91b0fe2cc8e7e6742b85e47d6120a204f70ed9fad7829cf03",
          "sha256": "a68a43a5fc40c2bb04718296a00142ee5240ceb5dfa50807d19a98c7e245b7e7",
          "sha1": "ef1f16ce7900f602826b985f15b67bbe60015a08",
          "md5": "a89de3fa1c4e19fc8796e776ab58428d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-config-6.2.4-javadoc.jar",
          "url": "spring-security-config-6.2.4-javadoc.jar",
          "size": 1113942,
          "sha512": "25e3b0e1fa654b4626f26f7bc351d539ffe650995c03adbf50d97bd74e685aada9c614947fe42b33fee56dad6ba77239ee4246c098c3001acf3c0907d079c626",
          "sha256": "ff72ea49f67690526cf5a9f1bbd456534da8f2e20632e20c3bf9fc9b6ca47a9e",
          "sha1": "45601ed0615a14289009b9483ccec43c13e5f3cd",
          "md5": "2ecf80544e357727ee58bd4fc9a5da3f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-config-6.2.4-sources.jar",
          "url": "spring-security-config-6.2.4-sources.jar",
          "size": 1250354,
          "sha512": "400d95002f500d6d04725e36023e4c8b490a01dd2481ddef2e875ff784353ae3910bde82e5a9b8d45109a46a6670c6d537fa78daee770fd620cd696d4ef2ecbb",
          "sha256": "a002d87ab6366cfeb55ddc10369d35b54e9c090e24deb6227ff2956d31e2d8d4",
          "sha1": "53acc2ff41587d26c6447718aedb76022bf09efe",
          "md5": "76863bf261c7995cdb90fb9dc0880570"
        },
        {
          "name": "spring-security-config-6.2.4-sources.jar",
          "url": "spring-security-config-6.2.4-sources.jar",
          "size": 1250354,
          "sha512": "400d95002f500d6d04725e36023e4c8b490a01dd2481ddef2e875ff784353ae3910bde82e5a9b8d45109a46a6670c6d537fa78daee770fd620cd696d4ef2ecbb",
          "sha256": "a002d87ab6366cfeb55ddc10369d35b54e9c090e24deb6227ff2956d31e2d8d4",
          "sha1": "53acc2ff41587d26c6447718aedb76022bf09efe",
          "md5": "76863bf261c7995cdb90fb9dc0880570"
        }
      ]
    }
  ]
}
