{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webflux",
    "version": "6.1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webflux-6.1.6.jar",
          "url": "spring-webflux-6.1.6.jar",
          "size": 978864,
          "sha512": "6b81fe5df79bf8401411dc73410285fbf6bfb6b4062a3a788180b8b4b3ac10802a3db5b2f4cc682133267e1cb411df23efe688f4504a85ab6a2407f26da80766",
          "sha256": "2006a403cce2fa7b377fdf2a231f80638347d4a19ed8ef9bbe577d749de07c9b",
          "sha1": "5d315dbc075c81ec72440de976eea70e082602d0",
          "md5": "d1170643d09926037835a4ef15778849"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "io.projectreactor",
          "module": "reactor-core",
          "version": {
            "requires": "3.6.5"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webflux-6.1.6.jar",
          "url": "spring-webflux-6.1.6.jar",
          "size": 978864,
          "sha512": "6b81fe5df79bf8401411dc73410285fbf6bfb6b4062a3a788180b8b4b3ac10802a3db5b2f4cc682133267e1cb411df23efe688f4504a85ab6a2407f26da80766",
          "sha256": "2006a403cce2fa7b377fdf2a231f80638347d4a19ed8ef9bbe577d749de07c9b",
          "sha1": "5d315dbc075c81ec72440de976eea70e082602d0",
          "md5": "d1170643d09926037835a4ef15778849"
        }
      ]
    }
  ]
}
