spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  secret: "${JWT_SECRET}"
  access-exp-seconds: 86400 # 1일
  refresh-exp-seconds: 2592000 # 30일

logging:
  level:
    org.springframework.security: DEBUG

server:
  forward-headers-strategy: framework

kakao:
  auth:
    base-url: https://kapi.kakao.com
  local:
    base-url: https://dapi.kakao.com
    rest-api-key: ${KAKAO_REST_API_KEY}
