{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-web",
    "version": "6.2.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-web-6.2.4.jar",
          "url": "spring-security-web-6.2.4.jar",
          "size": 781165,
          "sha512": "4f6df6122e8f794692b52dbdbf319d251e6fefa3f7775cc33c69e0f1f3b9b0c1b2649bc2b5b6648d6242d641195165df9124cdff93f388dc548ac98c235b13ec",
          "sha256": "53d902c7d7b216e19e595e4ab09a449a4a57011bb1cda1756cb7214059f3627c",
          "sha1": "b4a436865cf6483e088c986432f44d9e90bab6a3",
          "md5": "9a60d4e77f418ac926b7f1695bf12229"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-web-6.2.4.jar",
          "url": "spring-security-web-6.2.4.jar",
          "size": 781165,
          "sha512": "4f6df6122e8f794692b52dbdbf319d251e6fefa3f7775cc33c69e0f1f3b9b0c1b2649bc2b5b6648d6242d641195165df9124cdff93f388dc548ac98c235b13ec",
          "sha256": "53d902c7d7b216e19e595e4ab09a449a4a57011bb1cda1756cb7214059f3627c",
          "sha1": "b4a436865cf6483e088c986432f44d9e90bab6a3",
          "md5": "9a60d4e77f418ac926b7f1695bf12229"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-web-6.2.4-javadoc.jar",
          "url": "spring-security-web-6.2.4-javadoc.jar",
          "size": 1802899,
          "sha512": "7163835a1dc32a2bec0b9758e15a81735de475e99af53e782b9cf7ebc565f52c0f9201ad81bf0dfc73b92bbed5a3b73ec818fa3e9eca8098f9887a1ca148b3c5",
          "sha256": "8f4676e31f59f814cb420cbb091742be58f70c6cd6baf12d2b59998058fec347",
          "sha1": "03b6bf4f3fabb418debdd5aba3a83509a6419dc7",
          "md5": "661ef8c9dd430bd6373c51d104ca1b3a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-web-6.2.4-sources.jar",
          "url": "spring-security-web-6.2.4-sources.jar",
          "size": 644933,
          "sha512": "c7d02089a3be5914f3a726ca7c03063f45ff915d0814be81131c23b8f61123896161969e0505a80c35342f671d228f5763c2995673622490dcd0a44a351229be",
          "sha256": "22e027e97893aaa97bdd45730ccdd69a815f7884e8d6a154bce1233a931ace15",
          "sha1": "d8a00548af4592ade6fbc51e9325b332be4ec3c8",
          "md5": "9c863007be1b6d47e9842e78a2426fef"
        }
      ]
    }
  ]
}
